#!/usr/bin/env bash
# Edit the 'hosts' file
# localhost to resolve to 127.0.0.2
# facebook to resolve to 8.8.8.8

# a different way using ifconfig but now ip is a new command and ifconfig can be missing in some os
#ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | awk '{print $2}'


ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1
